export interface IMusicAlbum  {
    amgArtistId: number,
    artistId: number,
    artistName: string,
    artistViewUrl: string,
    artworkUrl100: string,
    artworkUrl60: string,
    collectionCensoredName: string,
    collectionExplicitness: string,
    collectionId: number,
    collectionName: string,
    collectionPrice: number,
    collectionType: "Album",
    collectionViewUrl: string,
    copyright: string,
    country: "GBR",
    currency: "GBP",
    primaryGenreName: string,
    releaseDate: Date,
    trackCount: number,
    wrapperType: "collection" | "track",
}


export interface IMovie  {
    amgArtistId: number,
    artistId: number,
    artistName: string,
    artistViewUrl: string,
    artworkUrl100: string,
    artworkUrl60: string,
    trackCensoredName: string,
    trackExplicitness: string,
    trackId: number,
    trackName: string,
    trackPrice: number,
    trackType: "Album",
    trackViewUrl: string,
    copyright: string,
    country: "GBR",
    currency: "GBP",
    primaryGenreName: string,
    releaseDate: Date,
    trackCount: number,
    wrapperType: "collection" | "track",
}